name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-static-analysis:
    name: Linting and Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify backend/app.py Exists
        run: |
          if [ ! -f "backend/app.py" ]; then
            echo "Error: backend/app.py not found."
            exit 1
          fi

      - name: Install Python Linting Tools
        run: |
          pip install flake8 bandit

      - name: Lint Python Code
        run: |
          flake8 backend/app.py
          bandit -r backend/app.py

      - name: Lint JavaScript Code
        working-directory: frontend
        run: |
          npm install eslint --save-dev
          npx eslint script.js

  unit-tests:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Dependencies & Run Tests
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest tests --maxfail=5 --disable-warnings

  vulnerability-scanning:
    name: Vulnerability Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify backend/app.py Exists
        run: |
          if [ ! -f "backend/app.py" ]; then
            echo "Warning: backend/app.py not found, skipping security scan."
            exit 0  # Exit gracefully instead of failing the pipeline
          fi

      - name: Install Security Tools
        run: |
          pip install safety bandit

      - name: Scan Python Dependencies
        run: |
          safety check -r backend/requirements.txt
          bandit -r backend/app.py

      - name: Audit NPM Dependencies
        working-directory: frontend
        run: |
          npm install
          npm audit --audit-level=high

  dast-dynamic-security-scan:
    name: Perform Dynamic Security Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Flask App in Background
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python app.py &  # Start Flask app in background
          sleep 10  # Give it time to start

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker pull owasp/zap2docker-stable
          docker run -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:5000 -r report.html

      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: report.html
